# Generated by Django 2.2.3 on 2019-07-31 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Taken'), (2, 'Reissued'), (3, 'On approve'), (4, 'Done')], default=0),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='task.Task'),
        ),
    ]
